// Mocks generated by Mockito 5.4.6 from annotations
// in soundcloud_clone/test/features/messaging/presentation/providers/conversations_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:soundcloud_clone/features/messaging/domain/entities/conversation.dart'
    as _i5;
import 'package:soundcloud_clone/features/messaging/domain/entities/message.dart'
    as _i2;
import 'package:soundcloud_clone/features/messaging/domain/entities/participant.dart'
    as _i6;
import 'package:soundcloud_clone/features/messaging/domain/repositories/messaging_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMessage_0 extends _i1.SmartFake implements _i2.Message {
  _FakeMessage_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MessagingRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMessagingRepository extends _i1.Mock
    implements _i3.MessagingRepository {
  MockMessagingRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.Conversation>> getConversations({
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getConversations,
          [],
          {
            #page: page,
            #limit: limit,
          },
        ),
        returnValue:
            _i4.Future<List<_i5.Conversation>>.value(<_i5.Conversation>[]),
      ) as _i4.Future<List<_i5.Conversation>>);

  @override
  _i4.Future<List<_i2.Message>> getMessages(
    String? conversationId, {
    int? page = 1,
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMessages,
          [conversationId],
          {
            #page: page,
            #limit: limit,
          },
        ),
        returnValue: _i4.Future<List<_i2.Message>>.value(<_i2.Message>[]),
      ) as _i4.Future<List<_i2.Message>>);

  @override
  _i4.Future<_i2.Message> sendMessage({
    required String? receiverId,
    String? content,
    String? conversationId,
    String? attachmentType,
    String? attachmentId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendMessage,
          [],
          {
            #receiverId: receiverId,
            #content: content,
            #conversationId: conversationId,
            #attachmentType: attachmentType,
            #attachmentId: attachmentId,
          },
        ),
        returnValue: _i4.Future<_i2.Message>.value(_FakeMessage_0(
          this,
          Invocation.method(
            #sendMessage,
            [],
            {
              #receiverId: receiverId,
              #content: content,
              #conversationId: conversationId,
              #attachmentType: attachmentType,
              #attachmentId: attachmentId,
            },
          ),
        )),
      ) as _i4.Future<_i2.Message>);

  @override
  _i4.Future<List<_i6.Participant>> searchUsers(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchUsers,
          [query],
        ),
        returnValue:
            _i4.Future<List<_i6.Participant>>.value(<_i6.Participant>[]),
      ) as _i4.Future<List<_i6.Participant>>);

  @override
  _i4.Future<List<_i6.Participant>> getFollowing(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFollowing,
          [userId],
        ),
        returnValue:
            _i4.Future<List<_i6.Participant>>.value(<_i6.Participant>[]),
      ) as _i4.Future<List<_i6.Participant>>);

  @override
  _i4.Future<void> markAsRead(String? conversationId) => (super.noSuchMethod(
        Invocation.method(
          #markAsRead,
          [conversationId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.Message> editMessage(
    String? messageId,
    String? content,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #editMessage,
          [
            messageId,
            content,
          ],
        ),
        returnValue: _i4.Future<_i2.Message>.value(_FakeMessage_0(
          this,
          Invocation.method(
            #editMessage,
            [
              messageId,
              content,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Message>);

  @override
  _i4.Future<void> deleteMessageForEveryone(String? messageId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteMessageForEveryone,
          [messageId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
